version: 2.1

jobs:
  test_and_build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: npm ci
      - run: npm t
  test_in_browser:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: sudo apt-get install xvfb
      - run: npm ci
      - run: xvfb-run --auto-servernum npm run test:browser

workflows:
  version: 2
  test_and_build:
    jobs:
      - test_and_build
      - test_in_browser
